#!/usr/bin/python3
"""
Module that handles basic JSON serialization and deserialization
of Python dictionaries to and from files.
"""


import json


def serialize_and_save_to_file(data, filename):
    """
    Serialize a Python dictionary and save it to a JSON file.

    Args:
        data (dict): Dictionary to serialize
        filename (str): Path to the JSON file to write.
    """
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(data, f)


def load_and_deserialize(filename):
    """
    Load a JSON file and deserialize it into a Python dictionary.

    Args:
        filename (str): Path to the JSON file to read.

    Returns:
        dict: Deserialized Python dictionary.
    """
    with open(filename, 'r', encoding='utf=8') as f:
        return json.load(f)
